sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
  - epmd -daemon
language: elixir
elixir:
    - 1.0.5
otp_release:
    - 17.5
    - 18.0
script: "MIX_ENV=test mix do deps.get, deps.compile, credo, test --cover"
